// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository_Layer;

namespace Repository_Layer.Migrations
{
    [DbContext(typeof(CRMdbContext))]
    partial class CRMdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRM_Demo.Models.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Claim_Type");

                    b.HasKey("Id")
                        .HasName("Claims_Id");

                    b.ToTable("Claim");
                });

            modelBuilder.Entity("Domain_Layer.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CourseAvaiStatus")
                        .HasColumnType("bit")
                        .HasColumnName("Course_AvaiStatus");

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Course_Description");

                    b.Property<TimeSpan>("CourseDuration")
                        .HasColumnType("time")
                        .HasColumnName("Course_Duration");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Course_Name");

                    b.Property<int>("CoursePrice")
                        .HasColumnType("int")
                        .HasColumnName("Course_Price");

                    b.Property<DateTime>("CourseRecordDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Course_Record_Date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("CourseUpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Course_Update_Date")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("Course_Id");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Domain_Layer.Models.CourseEnquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Course_Email");

                    b.Property<int?>("CourseEnId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CourseErecordDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Course_ERecord_Date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("CourseEupdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Course_EUpdate_Date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CourseFullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Course_FullName");

                    b.Property<string>("CoursePhone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Course_Phone");

                    b.Property<string>("CourseStageStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Course_StageStatus");

                    b.Property<int>("CourseTestScore")
                        .HasColumnType("int")
                        .HasColumnName("Course_TestScore");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("courseenq_id");

                    b.HasIndex("CourseEnId");

                    b.ToTable("CourseEnquiry");
                });

            modelBuilder.Entity("Domain_Layer.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ResourceAvaiStatus")
                        .HasColumnType("bit")
                        .HasColumnName("Resource_AvaiStatus");

                    b.Property<string>("ResourceDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Resource_Description");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Resource_Name");

                    b.Property<int>("ResourcePrice")
                        .HasColumnType("int")
                        .HasColumnName("Resource_Price");

                    b.Property<DateTime>("ResourceRecordDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Resource_Record_Date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Resource_Type");

                    b.Property<DateTime>("ResourceUpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Resource_Update_Date")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("Resource_Id");

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("Domain_Layer.Models.ResourseEnquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ResourceEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Resource_Email");

                    b.Property<int?>("ResourceEnId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResourceErecordDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Resource_ERecord_Date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ResourceEupdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Resource_EUpdate_Date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ResourceFullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Resource_FullName");

                    b.Property<string>("ResourcePhone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Resource_Phone");

                    b.Property<bool>("ResourceStatus")
                        .HasColumnType("bit")
                        .HasColumnName("Resource_Status");

                    b.HasKey("Id")
                        .HasName("Resenq_Id");

                    b.HasIndex("ResourceEnId");

                    b.ToTable("ResourseEnquiry");
                });

            modelBuilder.Entity("Domain_Layer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("UserClaimId")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("User_Email");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("User_Name");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("User_Password");

                    b.Property<string>("UserPhoneN")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("User_PhoneN");

                    b.Property<DateTime>("UserRecordDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("User_Record_Date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("UserUpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("User_Update_Date")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("Userman_Id");

                    b.HasIndex("UserClaimId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Domain_Layer.Models.CourseEnquiry", b =>
                {
                    b.HasOne("Domain_Layer.Models.Course", "CourseEn")
                        .WithMany("CourseEnquiries")
                        .HasForeignKey("CourseEnId")
                        .HasConstraintName("FK__CourseEnq__Cours__2D27B809");

                    b.Navigation("CourseEn");
                });

            modelBuilder.Entity("Domain_Layer.Models.ResourseEnquiry", b =>
                {
                    b.HasOne("Domain_Layer.Models.Resource", "ResourceEn")
                        .WithMany("ResourseEnquiries")
                        .HasForeignKey("ResourceEnId")
                        .HasConstraintName("FK__ResourseE__Resou__300424B4");

                    b.Navigation("ResourceEn");
                });

            modelBuilder.Entity("Domain_Layer.Models.User", b =>
                {
                    b.HasOne("CRM_Demo.Models.Claim", "UserClaim")
                        .WithMany("Users")
                        .HasForeignKey("UserClaimId")
                        .HasConstraintName("FK__User__User_Claim__30F848ED");

                    b.Navigation("UserClaim");
                });

            modelBuilder.Entity("CRM_Demo.Models.Claim", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain_Layer.Models.Course", b =>
                {
                    b.Navigation("CourseEnquiries");
                });

            modelBuilder.Entity("Domain_Layer.Models.Resource", b =>
                {
                    b.Navigation("ResourseEnquiries");
                });
#pragma warning restore 612, 618
        }
    }
}
